### PR TITLE
Added PushButton support and activeLow support

### LINKED ISSUE #26: Pin should have an "activeLow" configuration to allow On to be interpreted as 0
From the mailing list: https://discourse.mozilla.org/t/redefining-the-on-off-switch-thing/33890/2

### LINKED ISSUE #27: Add PushButton support
How do i add the pushbutton capability to my gateway? i just set it up and only have on/off capability.

thanks

### PR DESCRIPTION
**Pull request by dhylands**
Fixes #26
Fixes #27

### CODE REVIEW

**Review by mrstegeman — COMMENTED** [review]
Code looks fine, but I have a general question.

Should the user be able to configure whether they want a PushButton or a BinarySensor? It seems redundant, and maybe even confusing, to have both.

**Comment by dhylands** [comment]
I think the difference is really semantics. The pushed property and on property will always wind up being in sync, so it really boils down to what the user has connected to the pin.

What would be ideal is if the choice was pushed back down to the adapter so that it could advertise just the appropriate properties.

Either that or we add a configuration option to indicate whether a push button or binary sensor is connected and then the adapter will only present the configured option.

**Comment by mrstegeman** [comment]
> Either that or we add a configuration option to indicate whether a push button or binary sensor is connected and then the adapter will only present the configured option.

This is what I'd prefer. The user already has to manually configure all of their pins, so it makes sense to require this as part of the pin setup.

**Comment by dhylands** [comment]
OK - PushButton versus BinarySensor is now a config option.

Aside: I noticed that if I change the direction from BinarySensor to PushButton then the properties get updated automagically, but the type of the input changes to a generic thing rather than PushButton. I have to remove the thing, disable the gpio adapter and re-enable it and re-add then it will show up properly. I think others have reported this problem with other adapters as well.

**Review by mrstegeman — APPROVED** [review]

**Pull request merged**
